name: Static Code Analysis
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Molecule Lint
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: set -e yamllint . ansible-lint .
          molecule_command: lint
        env:
          ANSIBLE_FORCE_COLOR: '1'