---
name: Static Code Analysis
on: [push, pull_request]

jobs:
  ansiblelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: dsz182/ansible-lint
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint
        uses: frenck/action-yamllint@v1.1.2
        with:
          path: "ansible"